"""init_db

Revision ID: 1b834e97e0ad
Revises:
Create Date: 2026-07-29 04:24:37.124684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b834e97e0ad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellite_metadata",
        sa.Column(
            "norad_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("cospar_id", sa.String(length=15), nullable=False),
        sa.Column(
            "classification",
            sa.CHAR(length=1),
            server_default="U",
            nullable=False,
        ),
        sa.Column("launch_year", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "launch_year >= 1957", name="check_valid_launch_year"
        ),
        sa.CheckConstraint("norad_id > 0", name="check_positive_norad_id"),
        sa.PrimaryKeyConstraint("norad_id"),
        sa.UniqueConstraint("cospar_id", name="uq_satellite_cospar_id"),
    )
    op.create_table(
        "orbit_history",
        sa.Column("norad_cat_id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.DateTime(), nullable=False),
        sa.Column("object_name", sa.String(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("mean_motion", sa.FLOAT(), nullable=False),
        sa.Column("eccentricity", sa.FLOAT(), nullable=False),
        sa.Column("inclination", sa.FLOAT(), nullable=False),
        sa.Column("ra_of_asc_node", sa.FLOAT(), nullable=False),
        sa.Column("arg_of_pericenter", sa.FLOAT(), nullable=False),
        sa.Column("mean_anomaly", sa.FLOAT(), nullable=False),
        sa.Column(
            "ephemeris_type", sa.INTEGER(), server_default="0", nullable=False
        ),
        sa.Column(
            "classification_type",
            sa.CHAR(length=1),
            server_default="U",
            nullable=False,
        ),
        sa.Column(
            "element_set_no",
            sa.INTEGER(),
            server_default="999",
            nullable=False,
        ),
        sa.Column("rev_at_epoch", sa.INTEGER(), nullable=False),
        sa.Column("bstar", sa.FLOAT(), server_default="0.0", nullable=False),
        sa.Column(
            "mean_motion_dot", sa.FLOAT(), server_default="0.0", nullable=False
        ),
        sa.Column(
            "mean_motion_ddot",
            sa.FLOAT(),
            server_default="0.0",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["norad_cat_id"],
            ["satellite_metadata.norad_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("norad_cat_id", "epoch"),
    )
    op.create_table(
        "tle_history",
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("epoch_timestamp", sa.DateTime(), nullable=False),
        sa.Column("raw_line1", sa.CHAR(length=69), nullable=False),
        sa.Column("raw_line2", sa.CHAR(length=69), nullable=False),
        sa.ForeignKeyConstraint(
            ["norad_id"], ["satellite_metadata.norad_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("norad_id", "epoch_timestamp"),
    )
    op.create_table(
        "calculation_tasks",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_points", sa.BIGINT(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("used_tle_norad_id", sa.Integer(), nullable=True),
        sa.Column("used_tle_epoch", sa.DateTime(), nullable=True),
        sa.Column("used_orbit_norad_id", sa.Integer(), nullable=True),
        sa.Column("used_orbit_epoch", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chunks_total", sa.SmallInteger(), nullable=False),
        sa.Column("chunks_done", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'success', 'failed')",
            name="ck_status",
        ),
        sa.CheckConstraint(
            "task_type IN ('fast', 'slow', 'precision')", name="ck_task_type"
        ),
        sa.CheckConstraint(
            "\n            (used_tle_norad_id IS NOT NULL AND used_tle_epoch IS NOT NULL\n            AND used_orbit_norad_id IS NULL AND used_orbit_epoch IS NULL)\n            OR\n            (used_orbit_norad_id IS NOT NULL AND used_orbit_epoch IS NOT NULL\n            AND used_tle_norad_id IS NULL AND used_tle_epoch IS NULL)\n            ",
            name="ck_single_source_data",
        ),
        sa.CheckConstraint(
            "start_time <= end_time", name="ck_valid_time_range"
        ),
        sa.ForeignKeyConstraint(
            ["used_orbit_norad_id", "used_orbit_epoch"],
            ["orbit_history.norad_cat_id", "orbit_history.epoch"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["used_tle_norad_id", "used_tle_epoch"],
            ["tle_history.norad_id", "tle_history.epoch_timestamp"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_satellite",
        "calculation_tasks",
        ["used_tle_norad_id"],
        unique=False,
    )
    op.create_index(
        "idx_tasks_status_created",
        "calculation_tasks",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_status_created", table_name="calculation_tasks")
    op.drop_index("idx_tasks_satellite", table_name="calculation_tasks")
    op.drop_table("calculation_tasks")
    op.drop_table("tle_history")
    op.drop_table("orbit_history")
    op.drop_table("satellite_metadata")
    # ### end Alembic commands ###
