"""init

Revision ID: 63ed37acf539
Revises:
Create Date: 2026-07-26 03:58:42.765912

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63ed37acf539"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellite_metadata",
        sa.Column(
            "norad_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("cospar_id", sa.CHAR(length=8), nullable=False),
        sa.Column(
            "classification",
            sa.CHAR(length=1),
            server_default="U",
            nullable=False,
        ),
        sa.Column("launch_year", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "launch_year >= 1957", name="check_valid_launch_year"
        ),
        sa.CheckConstraint("norad_id > 0", name="check_positive_norad_id"),
        sa.PrimaryKeyConstraint("norad_id"),
        sa.UniqueConstraint("cospar_id", name="uq_satellite_cospar_id"),
    )
    op.create_table(
        "tle_history",
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("epoch_timestamp", sa.DateTime(), nullable=False),
        sa.Column("element_set_number", sa.Integer(), nullable=False),
        sa.Column("raw_line1", sa.CHAR(length=69), nullable=False),
        sa.Column("raw_line2", sa.CHAR(length=69), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["norad_id"], ["satellite_metadata.norad_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("norad_id", "epoch_timestamp"),
        postgresql_partition_by="RANGE (epoch_timestamp)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tle_history")
    op.drop_table("satellite_metadata")
    # ### end Alembic commands ###
