"""add task

Revision ID: eb4108c31c79
Revises: 63ed37acf539
Create Date: 2026-07-28 03:19:44.822010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb4108c31c79'
down_revision: Union[str, Sequence[str], None] = '63ed37acf539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_tasks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('total_points', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('used_tle_norad_id', sa.Integer(), nullable=False),
    sa.Column('used_tle_epoch', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('chunks_total', sa.SmallInteger(), nullable=False),
    sa.Column('chunks_done', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'success', 'failed')", name='ck_status'),
    sa.CheckConstraint("task_type IN ('fast', 'slow', 'precision')", name='ck_task_type'),
    sa.CheckConstraint('start_time <= end_time', name='ck_valid_time_range'),
    sa.ForeignKeyConstraint(['used_tle_norad_id', 'used_tle_epoch'], ['tle_history.norad_id', 'tle_history.epoch_timestamp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_satellite', 'calculation_tasks', ['used_tle_norad_id'], unique=False)
    op.create_index('idx_tasks_status_created', 'calculation_tasks', ['status', 'created_at'], unique=False)
    op.drop_column('tle_history', 'element_set_number')
    op.drop_column('tle_history', 'captured_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tle_history', sa.Column('captured_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tle_history', sa.Column('element_set_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_tasks_status_created', table_name='calculation_tasks')
    op.drop_index('idx_tasks_satellite', table_name='calculation_tasks')
    op.drop_table('calculation_tasks')
    # ### end Alembic commands ###
